language: generic

matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    sudo: required
    dist: trusty
    services: docker
    env: USE_PYTHON_VERSION=docker
  - os: linux
    sudo: required
    dist: xenial
    language: generic
    env: USE_PYTHON_VERSION=docker
  - os: linux
    env: USE_PYTHON_VERSION=py37
    language: python
    python: 3.7
    sudo: required
    dist: xenial
  - os: linux
    env: USE_PYTHON_VERSION=py38
    language: python
    python: 3.8
    sudo: required
    dist: xenial
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: USE_PYTHON_VERSION=py36
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: USE_PYTHON_VERSION=py37
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: USE_PYTHON_VERSION=py38
  - os: osx
    osx_image: xcode10.3 #macOS 10.14.4
    language: generic
    env: USE_PYTHON_VERSION=py38
  - os: osx
    osx_image: xcode11.2 #macOS 10.14
    language: generic
    env: USE_PYTHON_VERSION=py38
  - os: osx
    osx_image: xcode10.1 #macOS 10.13
    language: generic
    env: USE_PYTHON_VERSION=py38



install:
- if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker build -t genomematt/ambivert
  . ; fi
- if [[ "$USE_PYTHON_VERSION" != "docker" ]]; then bash ./.travis/install.sh ; echo
  "install.sh has run"; fi

script:
- if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker run -i genomematt/ambivert
  ambivert --test --version ; fi
- if [[ "$USE_PYTHON_VERSION" != "docker" ]]; then ambivert --test --version ; fi
