language: generic

matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    sudo: required
    dist: trusty
    services: docker
    env: USE_PYTHON_VERSION=docker
  - os: linux
    sudo: required
    dist: xenial
    language: generic
    env: USE_PYTHON_VERSION=docker
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: USE_PYTHON_VERSION=py37
  - os: linux
    sudo: required
    dist: xenial
    language: generic
    env: USE_PYTHON_VERSION=py37
  - os: osx
    osx_image: xcode8.3
    language: generic
    env: USE_PYTHON_VERSION=py36
  - os: osx
    osx_image: xcode8
    language: generic
    env: USE_PYTHON_VERSION=py36
  - os: osx
    osx_image: xcode7
    language: generic
    env: USE_PYTHON_VERSION=py36
  - os: osx
    osx_image: beta-xcode6.2
    language: generic
    env: USE_PYTHON_VERSION=py36

install:
- if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker build -t genomematt/ambivert
  . ; fi
- if [[ "$USE_PYTHON_VERSION" != "docker" ]]; then bash ./.travis/install.sh ; echo
  "install.sh has run"; fi

script:
- if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker run -i genomematt/ambivert
  ambivert --test --version ; fi
- if [[ "$USE_PYTHON_VERSION" != "docker" ]]; then ambivert --test --version ; fi
