# Due to a bug when building in the python2.x virtual env the Travis uses
# (even for python 3) we do this in the docker container
language: python

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      dist: trusty
      services: docker
      env: USE_PYTHON_VERSION=docker
    - os: osx
      osx_image: xcode7.2
      language: generic
      env: USE_PYTHON_VERSION=py35

before_install:
  - if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker build -t genomematt/ambivert . ; fi

script:
  # as ambivert --test runs inline we give it a valid --version task
  # so as to get a zero exit status
  - if [[ "$USE_PYTHON_VERSION" == "docker" ]]; then docker run -i genomematt/ambivert ambivert --test --version ; fi
