language: python
# force non container infrastructure for now
sudo: required
python:
  - "3.3"
  - "3.4"
  - "pypy3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools
install:
  - pip3 install .
before_script:
  - pip3 install coverage
  - pip3 install python-coveralls
# command to run tests, e.g. python setup.py test
script:
  - ls /home/travis/build/genomematt/AmBiVErT/ambivert/align/ 1>&2
  - python3 -m ambivert.tests.test_ambivert
#Coverage is currently failing to run so only doing standard tests until debugged
#  - coverage run --source ambivert.ambivert -m ambivert.tests.test_ambivert
#after_success:
#  - coveralls
